[package]
name = "snarc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.9.2"
hash40 = { version = "1.2.0", default-features = false }
paste = "1.0.8"
